[index]

description = "Tools for interacting with Todoist tasks"

tools = [
    "todoist.create_task",
    "todoist.get_tasks",
    "todoist.update_task",
    "todoist.close_task",
    "todoist.delete_task",
]
